### ISSUE TITLE
AZ 部分要如何申请？

### ISSUE THREAD

**Issue by Code-KaMyinn** [KusakabeSi/free365#19]
我成功的 偷渡到 A1P
https://od.obagg.com	crpolytechnic.in
但是 我不知道 如何 去申请 AZ
这个 crpolytechnic.in 是 没有OD
但是 你 标记了 AZ , 所以 我想试试看 申请 AZ

**Comment by KusakabeSi** [comment]
你可以去這邊申請試試，風控系統很嚴格， 需要乾淨的ip 手機號碼
Starter版: https://azure.microsoft.com/en-us/free/students/starter/
普通版: https://azure.microsoft.com/en-in/free/students/

以前都可以過普通版的，今年中開始一大部分域名被限制只能通過starter版了
請見此處: https://xrenblog.com/article/000007.html
API只能探測有AZ資格，不能知道是Starter還是普通版

普通版才能使用B1s VM
Starter版沒啥用，只能使用以下服務: https://azure.microsoft.com/zh-tw/offers/ms-azr-0144p/

**Comment by Code-KaMyinn** [comment]
谢谢你 的 回复
