### ISSUE TITLE
这两个 也无效了!

### ISSUE THREAD

**Issue by Code-KaMyinn** [KusakabeSi/free365#20]
http://24mail.chacuo.net	
@stu.mao.office.gy 

https://yopmail.com
@awzg.office.gy
@awzg.sch.lv

Woops!
From the email address you entered it looks like your school isn't on our list of eligible intitutions for free Office 365 Education. Please make sure to check your email below to ensure it was entered correctly.

**Comment by KusakabeSi** [comment]
Thank your report, I had been updated the list.
