### ISSUE TITLE
分享两个

### ISSUE THREAD

**Issue by nbtu** [KusakabeSi/free365#5]
之前那个xkx.me翻了，现在临时邮箱里面有个5tb.in的可用，可以申请一个防身

公众号 禾令奇 可以积分兑换/抽奖领A3，大概签到3天就能换到了

**Comment by KusakabeSi** [comment]
OK了，已加。感謝你的提供

**Comment by BsNgChiThanh** [comment]
How to create a permanent Office 365 A1 for admin account

**Comment by BsNgChiThanh** [comment]
for an Office A1 account for admin. Thank you

**Comment by BsNgChiThanh** [comment]
for an Office A1 account for admin. Thank you, my email driverbsthanh@gmail.com

**Comment by BsNgChiThanh** [comment]
I Want Office 365 A3? Bro give acc, thank you.

**Comment by BsNgChiThanh** [comment]
I Want Office 365 A3? Bro give acc, thank you. My gmail: driverbsthanh@gmail.com

**Comment by BsNgChiThanh** [comment]
I want Office 365 A3, Bro give me acc. Thank you, my email driverbsthanh@gmail.com

**Comment by reel-9** [comment]
这个已经失效了。

**Comment by KusakabeShi** [comment]
OK
