### ISSUE TITLE
失效报告

### ISSUE THREAD

**Issue by xJogger** [KusakabeSi/free365#6]
https://a1_free365.a1od.workers.dev/
http://office.zx.al/
以上两个已经失效，具体表现为可以注册，注册之后可以登录，但是登录之后打开Onedrive会提示遇到错误，应该是SPO限额已经被微软调整为0了。
https://od.wasonliu.workers.dev/
这个注册之后可以正常打开Onedrive。

**Comment by KusakabeSi** [comment]
SPO quota是檔案下載/上傳的限制

OD不能用不一定是被微軟後台歸0，可能只是剛好太多人用SPO quota被用光了。
有時要多觀察幾天看看，剛剛看還能用。應該還沒翻車

不過一個全局太多人的話，就算微軟沒限制，也很容易被大家用光就是了(也離翻車不遠了)
